// scripts/set-env.js
const { writeFileSync } = require('fs');
const dotenv = require('dotenv');
const dotenvExpand = require('dotenv-expand');

// هل تم تمرير --prod ؟
const isProd = process.argv.includes('--prod');
const envFile = isProd ? '.env.production' : '.env';

// حمل القيم من الملف
dotenvExpand.expand(dotenv.config({ path: envFile }));

// ثبّت هنا إعدادات Firebase العامة (مش أسرار) — عدّليها لو احتجتِ
const firebaseConfig = {
  apiKey: 'AIzaSyCcTXUVxwtZfxZ_-8nCOoeYTb3aSxBDRMg',
  authDomain: 'media-app-80c75.firebaseapp.com',
  projectId: 'media-app-80c75',
  storageBucket: 'media-app-80c75.firebasestorage.app',
  messagingSenderId: '133933542668',
  appId: '1:133933542668:web:77ec37854254e7ba7d6d29'
};

const targetPath = isProd
  ? './src/environments/environment.prod.ts'
  : './src/environments/environment.ts';

const fileContents = `// Auto-generated by scripts/set-env.js (${envFile})
export const environment = {
  production: ${isProd},
  firebase: ${JSON.stringify(firebaseConfig, null, 2)},
  geminiApiKey: "${process.env.GEMINI_API_KEY ?? ''}",
  tmdbApiToken: "${process.env.TMDB_API_TOKEN ?? ''}"
};
`;

writeFileSync(targetPath, fileContents, { encoding: 'utf-8' });

